### ISSUE TITLE
language-configuration not found

### ISSUE THREAD

**Issue by meelix** [mun-lang/vscode-extension#15]
vscode can't find mun-lang.mun-0.2.1\language-configuration.json

Temp fix: Copying the file manually. Opening devtools [in the help menu] will show the path where the file is supposed to be

**Comment by Wodann** [comment]
Thank you for reporting the issue. We'll try to push a fix soon.

**Comment by baszalmstra** [comment]
I pushed just published `v0.2.2` where this issue should be fixed!
